require "./player"

class Question
    attr_accessor :turn

    def initialize(turn)
        @player1 = Player.new("Player 1")
        @player2 = Player.new("Player 2")
        @turn = turn
    end

    def generate_question
        # questins hould be generated by picking two random number from 0-20
        [rand(1..20), rand(1..20)]
    end


    def play
        if game_over
            exit
        end
        num1, num2 = generate_question
        actual = num1 + num2
        puts("")
        puts "------ NEW TURN ------"
        puts "#{current_player.name}: What is #{num1} + #{num2}?"
        print "> "
        expected = $stdin.gets.chomp.to_i()    

        if actual == expected
            puts "#{current_player.name}: You are correct! \u{1F44F}"
            puts ""
        else
            puts "#{current_player.name}: Seriously? No! \u{1F614}"
            puts " "
            current_player.reduce_life
        end

        update_turn(turn)
        puts "P1: #{@player1.lives}/3 lives | P2: #{@player2.lives}/3 lives"
        puts "****************************************"
    end

     # end game if any player has lost all their lives
    def game_over
        done = false
        if @player1.lives == 0 || @player2.lives == 0
            done = true            
            if @player1.lives > @player2.lives
                puts "Player 1 wins with #{@player1.lives} lives left!"                
            elsif @player2.lives > @player1.lives
                puts "Player 2 wins with #{@player2.lives} lives left!"                
            # else
            #     puts "It's a tie! Both players have #{@player2.lives}/3 lives."
                
            end
        puts "------ GAME OVER ------"
        puts "Good bye! \u{1F44B}"  
        end        
        return done
               
    end

    # get the proper turn
    def update_turn(turn)
        if turn == 1
            @turn = 2
        else
            @turn = 1
        end
    end

    # Set the current player
    def current_player
        if @turn == 1
            @player1
        else
            @player2
        end
    end
def asjcgdc
                puts()
end
end 